version: "3.8"
services:
  kafka1:
    image: suhail50/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: Test123
    volumes:
    - ./properties/server.properties:/kafka/config/kraft/server.properties
    - ./data:/tmp/kafka-logs