FROM eclipse-temurin:17-jre-focal

ADD https://dlcdn.apache.org/kafka/3.8.1/kafka_2.13-3.8.1.tgz kafka.tgz

RUN tar -xvzf kafka.tgz

RUN rm kafka.tgz

RUN mv /kafka_2.13-3.8.1 /kafka

ENV PATH=${PATH}:/kafka/bin

WORKDIR practice

ADD start.sh start.sh

CMD [ "sh", "start.sh" ]

